### PR TITLE
Add Renovate Dashboard issue and use lockFileMaintenance

### PR DESCRIPTION
**Pull request by HonkingGoose**
## What changes?

- Enable Renovate dashboard
- Enable lockfile maintenance on Mondays
- Add basic automerge (see post below for some serious warnings, and ways to get proper advice)

## Why you might like these changes:

You can use the dashboard to get a overview of all that the bot's doing on your repository.
This is handy if you hold back updates (you can see all the updates you've held back in the dashboard).

The lock file maintenance ensures that your lockfile is kept up to date (if you use one).
By default Renovate will make a PR on Monday that updates the lockfile dependencies but you can adjust this schedule.

Let me know what you think. :wink: 

## Renovate documentation links:

[lockFileMaintenance](https://docs.renovatebot.com/configuration-options/#lockfilemaintenance)
[dependencyDashboard](https://docs.renovatebot.com/configuration-options/#dependencydashboard)

### CODE REVIEW

**Comment by travi** [comment]
i definitely want to enable the lockfile-maintenance. we dont currently use lockfiles, mostly because they become stale over time. i want to start using lockfiles, but maintenance like this would be a requirement, so this setting is certainly on my list.

in my own projects, i'm pretty aggressive about auto-merging. i expect that we will avoid that in this project for the most part, at least to start with. however, i would be interested in auto-merging the lockfile updates since they only impact maintainers. do you happen to know if you can configure auto-merge only in that case to start with? i can dig for that info if you arent sure.

since i normally auto-merge, i normally leave the dashboard disabled. i think i'm interested in input from @gr2m on whether we want to try that piece out.

**Comment by HonkingGoose** [comment]
I've made a basic automerge configuration. For a really simple repository this should work, but the problem is that your repositories are more complicated and have more moving parts.

## WARNING: the default automerge will probably not work right away

There are some dragons with regards to:

- Codeowners that must review certain files
- The absence of tests on a repo (this can be worked around in the Renovate config though :wink:)
- Required reviews on PRs
- Branch protection rules

I'm only confident that I can help with the absence of tests workaround.

I know that the Renovate repo themselves use a second bot to approve the automerge PRs, but you'll have to ask them how they got that working, as I'm not sure how they're doing that.

I don't really know how to fix problems with codeowners, required reviews on PRs or branch protection rules.

I recommend that you let the Renovate team help us with getting automerge working properly. Open a issue at: https://github.com/renovatebot/config-help/issues and copy/paste the current config into the issue.

## What the Renovate docs say about automerge:

**Automerge makes a PR by default:**

>Automerging defaults to using Pull Requests. In that case Renovate first creates a branch, then an associated Pull Request, and then automerges the first time it detects that the Pull Requests status checks are "green".

**If you don't have tests on a repo, you'll need to tell Renovate to ignore the requiredStatusCheck:**

> Note: if you have no tests but still want Renovate to automerge, you need to add `"requiredStatusChecks": null` to your configuration.

This is a big gotcha, if you intend to use automerge on a repo without tests, you need to add the "ignore tests" option.

**Renovate won't automerge when a PR has a negative review**

> Important: Renovate won't automerge on GitHub if a PR has a negative review outstanding.

**You can let Renovate automerge in the background without a PR**

> If you prefer that Renovate more silently automerge without Pull Requests at all, you can configure "automergeType": "branch".

**Comment by gr2m** [comment]
Is there an example of a Renovate dashboard issue? I'm not sure if we need it, sounds like something you'd do when things become hard to oversee. I'd start without it.

We do enforce pull request reviews. But it would be simple enough to write an action that creates a review for very specific pull requests so that the auto-merge is not blocked. Updating lock files ones per weeks sounds like a good idea.

**Comment by HonkingGoose** [comment]
> Is there an example of a Renovate dashboard issue?

Go to the https://github.com/renovatebot/renovate/issues and click on the pinned "Dependency Dashboard" issue to see the dashboard in action.

> I'm not sure if we need it, sounds like something you'd do when things become hard to oversee.

You do not **need** it, but it can be handy.

Renovate themselves list these benefits:

* View all PRs in one place, rather than having to filter PRs by author
* Rebase/retry multiple PRs without having to open each individually
* Override any rate limiting (e.g. concurrent PRs) or scheduling to force Renovate to create a PR that would otherwise be suppressed
* Recreate an unmerged PR (e.g. for a major update that you postponed by closing the original PR)

I also find it handy to have the dashboard, because I can then ask for a lock-file upgrade anytime I want (it's always visible on the dashboard as a scheduled upgrade). So if you really need to upgrade the lockfile now (say a security patch comes in for a dependency), you can click on the checkbox and get a fresh lockfile from the bot.

See https://docs.renovatebot.com/configuration-options/#dependencydashboard for the docs on the dashboard.

**Comment by travi** [comment]
this is the bot they use, so i'm hopeful that it can simplify that piece: https://github.com/renovatebot/renovate-approve-bot

**Comment by HonkingGoose** [comment]
I also found this: https://github.com/apps/renovate-approve that might be even easier... :smile: 

This app is made by Renovate themselves.

---

**Verbatim quotes of linked page:**

Use this bot if you need to automatically approve WhiteSource Renovate's Pull Requests automerging PRs, in cases where GitHub's branch protection is enabled.

The solution: This `renovate-approve` bot will add a review approving any Pull Request by WhiteSource Renovate if the PR is configured for automerging. This enables automerge without human intervention even if you have Pull Request Review restrictions enabled.

This Renovate Approve bot will not approve Pull Requests if they don't have automerge enabled. Otherwise the reviews would be pointless but add to your notification noise.

If you need two reviewers per PR, also install https://github.com/apps/renovate-approve-2

Important note: Due to a GitHub limitation, it is not possible to assign any app like this one as a CODEOWNER, so unfortunately this bot won't work that way if you have CODEOWNERS set up.

**Review by gr2m — APPROVED** [review]
Changes all look good to me 👍🏼 Thanks for all the explanations! Shall I install https://github.com/apps/renovate-approve on all repos?

**Comment by travi** [comment]
> Shall I install github.com/apps/renovate-approve on all repos?

i think that makes sense, yeah

**Comment by gr2m** [comment]
app is installed. Unless you want to add anything else to the central config, let's merge

**Comment by travi** [comment]
i'm sure we'll have some more tweaks over time, but i'm good with this adjustment for now

**Comment by HonkingGoose** [comment]
Thanks for merging in my changes. :+1:

**Comment by travi** [comment]
we appreciate the help and the nudge to move this forward

**Comment by HonkingGoose** [comment]
You might want to **pin** the Renovate "Dependency Dashboard" issue, so that you can always find it in the issue list for your repository. This will probably make it way easier for you to administer all those repositories under the Semantic Release umbrella. If you pin all the Dashboards, you can always find them in the same spot in each repo.

See the [GitHub docs on pinning an issue](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/pinning-an-issue-to-your-repository).

**Pull request merged**
