### PR TITLE
feat(renovate): configured to auto-merge dev-deps using the branch strategy

### LINKED ISSUE #3: Some automerge thoughts
I deliberately gave you a really simple automerge config, it's tricky to get this right the first time out of the gate, and I don't want to create a mess in case I did something wrong. That said, there are some things you'll probably want to tweak later on.

**What type of dependencies are automerged**

Right now you only get lockfile updates on Monday, that should be automerged.

I understand that you might want to automerge devDependencies next, that should be somewhat safe, provided you have test coverage.

**Renovate bothers me with PRs for automerged dependencies**

Each time Renovate opens a PR you get a GitHub notification for it if you're following the repo (which as maintainer, you probably are...). It will probably annoy you to get notified about a PR that's automerged succesfully anyways.

Luckily Renovate has an option that we can configure called `automergeType:branch` to make the automerge process as silent as it can be.

Quote from the [Renovate docs on the automergeType setting](https://docs.renovatebot.com/configuration-options/#automergetype):

> If you prefer that Renovate more silently automerge _without_ Pull Requests at all, you can configure `"automergeType": "branch"`. In this case Renovate will:
>
>  1. Create the branch, wait for test results
>  2. Rebase it any time it gets out of date with the base branch
>  3. Automerge the branch commit if it's: (a) up-to-date with the base branch, and (b) passing all tests
>  4. As a backup, raise a PR only if either: (a) tests fail, or (b) tests remain pending for too long (default: 24 hours)

**I need more documentation on this automerge thing, where can I find it**

You can search for the term `automerge` on the https://docs.renovatebot.com/configuration-options/ page of the docs to learn more.

### PR DESCRIPTION
**Pull request by travi**
so that noise from frequent update PRs is reduced

closes #3

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
looking forward to see this in action

**Comment by travi** [comment]
If all goes as planned, there shouldn't be much to see :)

**Comment by travi** [comment]
this one did get auto merged after i had approved before merging the config change: https://github.com/semantic-release/git/pull/217

**Comment by gr2m** [comment]
nice :)

**Comment by travi** [comment]
here is an example where the bot approved and it was auto-merged. still opened a PR tho

https://github.com/semantic-release/git/pull/221

**Comment by gr2m** [comment]
hmm any idea what might have happened @HonkingGoose?

**Comment by travi** [comment]
from https://docs.renovatebot.com/configuration-options/#automergetype, i'll bet it is because i forgot enable the branch builds since

> As a backup, raise a PR only if either: (a) tests fail, or (b) tests remain pending for too long (default: 24 hours)

**Comment by HonkingGoose** [comment]
> hmm any idea what might have happened @HonkingGoose?

Hi @gr2m,

@travi is right here, you need to enable CI builds for the `renovate/**` branches for automerge to work properly.

To be extra sure, I've already asked this question at the Renovate repo where I'm helping a bit with the `automerge-config` documentation:

https://github.com/renovatebot/renovate/pull/7724#issuecomment-728954627

I hope this is helpful.

Greetings HonkingGoose

**Comment by gr2m** [comment]
> you need to enable CI builds for the `renovate/**` branches for automerge to work properly

I'll script that

**Comment by gr2m** [comment]
done, here's the script: https://github.com/gr2m/run-test-action-workflow-on-renovate-branches/

**Pull request merged**
