### PR TITLE
chore: ignore package versions without CJS support

### PR DESCRIPTION
**Pull request by fgreinacher**
Related to https://github.com/semantic-release/semantic-release/issues/2133

### CODE REVIEW

**Review by travi — APPROVED** [review]
good call

**Comment by fgreinacher** [comment]
@travi WDYT we revert this now that the main package is migrated?

**Comment by travi** [comment]
i've been thinking about this too. the downside would be that we dont yet have all the impacted repos updated quite yet and it isnt clear yet how far we are from getting there. it has been nice for this to be in place to reduce the distracting PRs, but i dont think we'd want to move this to the individual repos temporarily either. 

i think i'm maybe thinking that we remove this once we get at least a couple of the official plugins fully converted to ESM. once we are there, i'd hope the repos where this would cause a negative impact would be faster to get resolved too.

please do keep reminding of this one, though. i do want to get it handled once the timing is a little better

**Comment by fgreinacher** [comment]
Sure, this makes sense! I’ll probably just override the relevant options locally to receive those updates!

**Pull request merged**
